# Generated by Django 5.2.17 on 2026-09-18 23:27
#
# Cria a linha única da submissão de trabalhos, já fechada. Assim a
# organização encontra o registro pronto no painel e no /admin/, em vez de
# ter que adivinhar que precisa criá-lo.

from django.db import migrations, models


def cria_a_linha(apps, schema_editor):
    Submissao = apps.get_model("eventos", "Submissao")
    Submissao.objects.get_or_create(pk=1, defaults={"aberta": False, "link": ""})


def apaga_a_linha(apps, schema_editor):
    apps.get_model("eventos", "Submissao").objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_inscricao_por_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta', models.BooleanField(default=False, help_text='Desmarcada, a página mostra “A submissão abre em breve”.', verbose_name='submissão aberta')),
                ('link', models.URLField(blank=True, help_text='Endereço do formulário de envio. Sem ele não aparece botão, mesmo com a submissão marcada como aberta.', max_length=300, verbose_name='link da submissão')),
                ('prazo', models.DateField(blank=True, help_text='Opcional. Sem data preenchida, a página não fala em prazo.', null=True, verbose_name='prazo de envio')),
            ],
            options={
                'verbose_name': 'submissão de trabalhos',
                'verbose_name_plural': 'submissão de trabalhos',
            },
        ),
        migrations.RunPython(cria_a_linha, apaga_a_linha),
    ]
