# Generated by Django 5.2.17 on 2026-09-19 01:36

import django.db.models.deletion
from django.db import migrations, models
#
# Semeia os sete cartões com exatamente o texto que já estava no template, para
# a página não mudar nada quando esta migração roda. Daqui em diante eles são
# editados no painel.

CARTOES = [
    {
        "slug": "cieec",
        "trilha": "CIEEC",
        "titulo": "Feira das Profissões e Empreendedorismo",
        "coordenacao": "CIEEC",
        "descricao": (
            "Espaço dedicado à orientação profissional e ao empreendedorismo, "
            "reunindo instituições de ensino, empresas parceiras e a Empresa "
            "Júnior. Inclui uma roda de conversa sobre profissões, "
            "empreendedorismo e mercado de trabalho."
        ),
        "rotulo": "27/10",
        "programacao": [
            "Feira das Profissões",
            "Espaço das Instituições de Ensino",
            "Feira de Empreendedorismo",
            "Estandes de empresas e instituições parceiras",
            "Empresa Júnior e projetos de empreendedorismo",
            "Roda de conversa: Profissões, Empreendedorismo e Mercado de Trabalho",
        ],
    },
    {
        "slug": "geral",
        "trilha": "Abertura oficial",
        "titulo": "Solenidade de Lançamento e Mostras",
        "coordenacao": "Comissão organizadora",
        "descricao": (
            "Cerimônia oficial de abertura da 23ª Semana Nacional de Ciência e "
            "Tecnologia, com mostras dos cursos técnicos e superiores do Campus."
        ),
        "rotulo": "28/10",
        "programacao": [
            "Cerimônia de abertura",
            "Mostras dos cursos técnicos e superiores",
        ],
    },
    {
        "slug": "agronomia-e-agropecuaria",
        "trilha": "Agronomia e Agropecuária",
        "titulo": "SIAAGRO — Seminário Integrado de Agropecuária e Agronomia",
        "coordenacao": "Coordenação de Agronomia e Agropecuária",
        "descricao": (
            "Seminário com oficinas, demonstrações e visitações voltadas à cadeia "
            "produtiva agropecuária, aberto a estudantes e à comunidade externa."
        ),
        "rotulo": "29 e 30/10",
        "programacao": ["Oficinas técnicas", "Demonstrações práticas", "Visitações guiadas"],
    },
    {
        "slug": "alimentos",
        "trilha": "Alimentos",
        "titulo": "Curso Técnico em Alimentos — Atividades da Semana",
        "coordenacao": "Coordenação do Curso Técnico em Alimentos",
        "descricao": (
            "Oficinas e demonstrações práticas de processamento e segurança de "
            "alimentos, conduzidas por estudantes e docentes do curso técnico."
        ),
        "rotulo": "29 e 30/10",
        "programacao": ["Oficinas práticas", "Demonstrações de processamento", "Visitações"],
    },
    {
        "slug": "informatica",
        "trilha": "Informática",
        "titulo": "IFROmatizando — III Workshop de Informática",
        "responsavel": "Eudóxia Moura",
        "coordenacao": "Coordenação de Informática",
        "descricao": (
            "Terceira edição do workshop de informática, com oficinas práticas e "
            "demonstrações de projetos de desenvolvimento de sistemas."
        ),
        "rotulo": "29 e 30/10",
        "programacao": [
            "Oficinas de programação",
            "Demonstrações de projetos",
            "Visitações ao laboratório",
        ],
    },
    {
        "slug": "biologia",
        "trilha": "Biologia",
        "titulo": "Biologia — Oficinas e Demonstrações",
        "coordenacao": "Coordenação de Biologia",
        "descricao": (
            "Atividades práticas e demonstrações voltadas à divulgação científica "
            "em Biologia, abertas a estudantes de outras escolas e à comunidade."
        ),
        "rotulo": "29 e 30/10",
        "programacao": ["Oficinas práticas", "Demonstrações", "Visitações"],
    },
    {
        "slug": "medicina-veterinaria",
        "trilha": "Medicina Veterinária",
        "titulo": "Medicina Veterinária — Oficinas e Demonstrações",
        "coordenacao": "Coordenação de Medicina Veterinária",
        "descricao": (
            "Oficinas, demonstrações e visitações voltadas à área de saúde e "
            "manejo animal."
        ),
        "rotulo": "29 e 30/10",
        "programacao": ["Oficinas práticas", "Demonstrações de manejo", "Visitações"],
    },
]


def cria_os_cartoes(apps, schema_editor):
    Area = apps.get_model("eventos", "Area")
    Cartao = apps.get_model("eventos", "Cartao")

    # Só semeia numa base que ainda não tem cartão nenhum: rodar de novo não
    # pode desfazer o que a organização já editou.
    if Cartao.objects.exists():
        return

    for ordem, dado in enumerate(CARTOES):
        area = Area.objects.filter(slug=dado["slug"]).first()
        if area is None:
            continue
        Cartao.objects.create(
            area=area,
            trilha=dado["trilha"],
            titulo=dado["titulo"],
            responsavel=dado.get("responsavel", ""),
            coordenacao=dado["coordenacao"],
            descricao=dado["descricao"],
            programacao_rotulo=dado["rotulo"],
            programacao="\n".join(dado["programacao"]),
            ordem=ordem,
        )


def apaga_os_cartoes(apps, schema_editor):
    apps.get_model("eventos", "Cartao").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_submissao_de_trabalhos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trilha', models.CharField(blank=True, help_text='O selo verde no alto do cartão. Em branco, usa o nome do curso/área.', max_length=60, verbose_name='etiqueta')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('responsavel', models.CharField(blank=True, help_text='Em branco, o cartão mostra “a confirmar”.', max_length=120, verbose_name='responsável')),
                ('coordenacao', models.CharField(blank=True, help_text='Vem depois do responsável, ex.: “Coordenação de Biologia”.', max_length=160, verbose_name='coordenação')),
                ('descricao', models.TextField(help_text='Duas ou três frases sobre o evento.', verbose_name='descrição')),
                ('programacao_rotulo', models.CharField(blank=True, help_text='Como aparece no cartão, ex.: “27/10” ou “29 e 30/10”.', max_length=40, verbose_name='data da programação')),
                ('programacao', models.TextField(blank=True, help_text='Um item por linha. Sem nenhum, o cartão não mostra a lista.', verbose_name='programação')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Menor primeiro. Em empate, vale o título.', verbose_name='ordem')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarque para tirar o cartão do site sem apagá-lo.', verbose_name='publicado')),
                ('area', models.ForeignKey(help_text='De onde vêm o botão de inscrição e o link do cronograma.', on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='eventos.area', verbose_name='curso/área')),
            ],
            options={
                'verbose_name': 'cartão da página inicial',
                'verbose_name_plural': 'cartões da página inicial',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.RunPython(cria_os_cartoes, apaga_os_cartoes),
    ]
