# Generated by Django 5.2.17 on 2026-09-20 18:49

from django.db import migrations, models
#
# O IFROmatizando publica a programação em página própria, então o botão
# "Ver horários" daquele cartão sai do site. Fica aqui para a página já subir
# apontando certo; daí em diante o endereço se troca no painel.

SITE_DO_IFROMATIZANDO = "https://sangalletti.github.io/IFROmatizando/"


def aponta_o_ifromatizando(apps, schema_editor):
    Cartao = apps.get_model("eventos", "Cartao")
    # `update` e não `save`: mexe só em quem ainda não tem link próprio, para
    # não desfazer um endereço que a organização já tenha trocado.
    Cartao.objects.filter(area__slug="informatica", link_horarios="").update(
        link_horarios=SITE_DO_IFROMATIZANDO
    )


def desaponta(apps, schema_editor):
    Cartao = apps.get_model("eventos", "Cartao")
    Cartao.objects.filter(link_horarios=SITE_DO_IFROMATIZANDO).update(link_horarios="")


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_cartoes_da_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='link_horarios',
            field=models.URLField(blank=True, help_text='Em branco, o botão “Ver horários” leva ao cronograma do site. Preenchido, leva a este endereço — para um curso que publique a programação em página própria.', max_length=300, verbose_name='link dos horários'),
        ),
        migrations.RunPython(aponta_o_ifromatizando, desaponta),
    ]
