# Generated by Django 5.2.17 on 2026-09-26 01:40

from django.db import migrations, models
#
# Os documentos da submissão — regulamento, modelos de trabalho. Tabela nova e
# vazia: nada do que já está no banco é tocado. A migração seguinte semeia os
# três que a organização já anunciou, sem arquivo ainda.


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_link_de_horarios_proprio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do título. É o endereço da versão do documento que fica no site.', max_length=120, unique=True, verbose_name='endereço curto')),
                ('descricao', models.CharField(blank=True, help_text='Uma linha explicando o que é. Opcional.', max_length=200, verbose_name='descrição')),
                ('arquivo', models.FileField(blank=True, help_text='PDF, DOCX, ODT… Deixe em branco se for usar um link, ou se o documento ainda não ficou pronto.', upload_to='submissao/', verbose_name='arquivo')),
                ('link', models.URLField(blank=True, help_text='Para um documento que já está publicado em outro lugar. Deixe em branco se enviou um arquivo.', max_length=300, verbose_name='link')),
                ('texto', models.TextField(blank=True, help_text='Opcional. Preenchido, o documento também ganha uma página no próprio site, para ler sem baixar nada — é o caso do regulamento. Uma linha começando com ## vira título; com - vira item de lista; linha em branco separa parágrafos.', verbose_name='texto no site')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Menor primeiro. Empate, ordena pelo título.', verbose_name='ordem')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarque para tirar da página sem apagar o documento.', verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'documento da submissão',
                'verbose_name_plural': 'documentos da submissão',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
